# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ServiceAdapterService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ServiceAdapterService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bServiceAdapterService.proto\"\x19\n\x17PendingDataCheckRequest\",\n\x18PendingDataCheckResponse\x12\x10\n\x08\x63lientId\x18\x01 \x03(\t\"^\n\x13\x45xchangeADUsRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x1a\n\x04\x61\x64us\x18\x02 \x03(\x0b\x32\x0c.AppDataUnit\x12\x19\n\x11lastADUIdReceived\x18\x03 \x01(\x03\"M\n\x14\x45xchangeADUsResponse\x12\x1a\n\x04\x61\x64us\x18\x01 \x03(\x0b\x32\x0c.AppDataUnit\x12\x19\n\x11lastADUIdReceived\x18\x02 \x01(\x03\"*\n\x0b\x41ppDataUnit\x12\r\n\x05\x61\x64uId\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\".\n\x0e\x43onnectionData\x12\x0f\n\x07\x61ppName\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"/\n\x0eResponseStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa1\x01\n\x15ServiceAdapterService\x12=\n\x0c\x65xchangeADUs\x12\x14.ExchangeADUsRequest\x1a\x15.ExchangeADUsResponse\"\x00\x12I\n\x10pendingDataCheck\x12\x18.PendingDataCheckRequest\x1a\x19.PendingDataCheckResponse\"\x00\x32_\n\x1dServiceAdapterRegistryService\x12>\n\x18\x63heckAdapterRegistration\x12\x0f.ConnectionData\x1a\x0f.ResponseStatus\"\x00\x42\x13\n\x0fnet.discdd.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ServiceAdapterService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017net.discdd.grpcP\001'
  _globals['_PENDINGDATACHECKREQUEST']._serialized_start=31
  _globals['_PENDINGDATACHECKREQUEST']._serialized_end=56
  _globals['_PENDINGDATACHECKRESPONSE']._serialized_start=58
  _globals['_PENDINGDATACHECKRESPONSE']._serialized_end=102
  _globals['_EXCHANGEADUSREQUEST']._serialized_start=104
  _globals['_EXCHANGEADUSREQUEST']._serialized_end=198
  _globals['_EXCHANGEADUSRESPONSE']._serialized_start=200
  _globals['_EXCHANGEADUSRESPONSE']._serialized_end=277
  _globals['_APPDATAUNIT']._serialized_start=279
  _globals['_APPDATAUNIT']._serialized_end=321
  _globals['_CONNECTIONDATA']._serialized_start=323
  _globals['_CONNECTIONDATA']._serialized_end=369
  _globals['_RESPONSESTATUS']._serialized_start=371
  _globals['_RESPONSESTATUS']._serialized_end=418
  _globals['_SERVICEADAPTERSERVICE']._serialized_start=421
  _globals['_SERVICEADAPTERSERVICE']._serialized_end=582
  _globals['_SERVICEADAPTERREGISTRYSERVICE']._serialized_start=584
  _globals['_SERVICEADAPTERREGISTRYSERVICE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
