# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ServiceAdapterService_pb2 as ServiceAdapterService__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ServiceAdapterService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceAdapterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.exchangeADUs = channel.unary_unary(
                '/ServiceAdapterService/exchangeADUs',
                request_serializer=ServiceAdapterService__pb2.ExchangeADUsRequest.SerializeToString,
                response_deserializer=ServiceAdapterService__pb2.ExchangeADUsResponse.FromString,
                _registered_method=True)
        self.pendingDataCheck = channel.unary_unary(
                '/ServiceAdapterService/pendingDataCheck',
                request_serializer=ServiceAdapterService__pb2.PendingDataCheckRequest.SerializeToString,
                response_deserializer=ServiceAdapterService__pb2.PendingDataCheckResponse.FromString,
                _registered_method=True)


class ServiceAdapterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def exchangeADUs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pendingDataCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceAdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'exchangeADUs': grpc.unary_unary_rpc_method_handler(
                    servicer.exchangeADUs,
                    request_deserializer=ServiceAdapterService__pb2.ExchangeADUsRequest.FromString,
                    response_serializer=ServiceAdapterService__pb2.ExchangeADUsResponse.SerializeToString,
            ),
            'pendingDataCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.pendingDataCheck,
                    request_deserializer=ServiceAdapterService__pb2.PendingDataCheckRequest.FromString,
                    response_serializer=ServiceAdapterService__pb2.PendingDataCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceAdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServiceAdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceAdapterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def exchangeADUs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceAdapterService/exchangeADUs',
            ServiceAdapterService__pb2.ExchangeADUsRequest.SerializeToString,
            ServiceAdapterService__pb2.ExchangeADUsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pendingDataCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceAdapterService/pendingDataCheck',
            ServiceAdapterService__pb2.PendingDataCheckRequest.SerializeToString,
            ServiceAdapterService__pb2.PendingDataCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceAdapterRegistryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkAdapterRegistration = channel.unary_unary(
                '/ServiceAdapterRegistryService/checkAdapterRegistration',
                request_serializer=ServiceAdapterService__pb2.ConnectionData.SerializeToString,
                response_deserializer=ServiceAdapterService__pb2.ResponseStatus.FromString,
                _registered_method=True)


class ServiceAdapterRegistryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkAdapterRegistration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceAdapterRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkAdapterRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.checkAdapterRegistration,
                    request_deserializer=ServiceAdapterService__pb2.ConnectionData.FromString,
                    response_serializer=ServiceAdapterService__pb2.ResponseStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceAdapterRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServiceAdapterRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceAdapterRegistryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkAdapterRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceAdapterRegistryService/checkAdapterRegistration',
            ServiceAdapterService__pb2.ConnectionData.SerializeToString,
            ServiceAdapterService__pb2.ResponseStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
